'''import urllib.request
import re
response = urllib.request.urlopen("file:///C:/docs/api/allclasses-frame.html")
html = response.read()
print(html)
html = html.decode("utf-8")
print(html)'''



content ='''<!-- NewPage -->
<html lang="en">
<head>
<!-- Generated by javadoc (1.8.0_333) on Tue Apr 26 05:55:54 GMT 2022 -->
<title>All Classes (Java Platform SE 8 )</title>
<meta name="date" content="2022-04-26">
<link rel="stylesheet" type="text/css" href="stylesheet.css" title="Style">
<script type="text/javascript" src="script.js"></script>
</head>
<body>
<h1 class="bar">All&nbsp;Classes</h1>
<div class="indexContainer">
<ul>
<li><a href="javax/swing/AbstractAction.html" title="class in javax.swing" target="classFrame">AbstractAction</a></li>
<li><a href="javax/lang/model/util/AbstractAnnotationValueVisitor6.html" title="class in javax.lang.model.util" target="classFrame">AbstractAnnotationValueVisitor6</a></li>
<li><a href="javax/lang/model/util/AbstractAnnotationValueVisitor7.html" title="class in javax.lang.model.util" target="classFrame">AbstractAnnotationValueVisitor7</a></li>
<li><a href="javax/lang/model/util/AbstractAnnotationValueVisitor8.html" title="class in javax.lang.model.util" target="classFrame">AbstractAnnotationValueVisitor8</a></li>
<li><a href="javax/swing/border/AbstractBorder.html" title="class in javax.swing.border" target="classFrame">AbstractBorder</a></li>
<li><a href="javax/swing/AbstractButton.html" title="class in javax.swing" target="classFrame">AbstractButton</a></li>
<li><a href="javax/swing/AbstractCellEditor.html" title="class in javax.swing" target="classFrame">AbstractCellEditor</a></li>
<li><a href="java/time/chrono/AbstractChronology.html" title="class in java.time.chrono" target="classFrame">AbstractChronology</a></li>
<li><a href="java/util/AbstractCollection.html" title="class in java.util" target="classFrame">AbstractCollection</a></li>
<li><a href="javax/swing/colorchooser/AbstractColorChooserPanel.html" title="class in javax.swing.colorchooser" target="classFrame">AbstractColorChooserPanel</a></li>
<li><a href="javax/swing/text/AbstractDocument.html" title="class in javax.swing.text" target="classFrame">AbstractDocument</a></li>
<li><a href="javax/swing/text/AbstractDocument.AttributeContext.html" title="interface in javax.swing.text" target="classFrame"><span class="interfaceName">AbstractDocument.AttributeContext</span></a></li>
<li><a href="javax/swing/text/AbstractDocument.Content.html" title="interface in javax.swing.text" target="classFrame"><span class="interfaceName">AbstractDocument.Content</span></a></li>
<li><a href="javax/swing/text/AbstractDocument.ElementEdit.html" title="class in javax.swing.text" target="classFrame">AbstractDocument.ElementEdit</a></li>
<li><a href="javax/lang/model/util/AbstractElementVisitor6.html" title="class in javax.lang.model.util" target="classFrame">AbstractElementVisitor6</a></li>
<li><a href="javax/lang/model/util/AbstractElementVisitor7.html" title="class in javax.lang.model.util" target="classFrame">AbstractElementVisitor7</a></li>
<li><a href="javax/lang/model/util/AbstractElementVisitor8.html" title="class in javax.lang.model.util" target="classFrame">AbstractElementVisitor8</a></li>
<li><a href="java/util/concurrent/AbstractExecutorService.html" title="class in java.util.concurrent" target="classFrame">AbstractExecutorService</a></li>
<li><a href="java/nio/channels/spi/AbstractInterruptibleChannel.html" title="class in java.nio.channels.spi" target="classFrame">AbstractInterruptibleChannel</a></li>
<li><a href="javax/swing/tree/AbstractLayoutCache.html" title="class in javax.swing.tree" target="classFrame">AbstractLayoutCache</a></li>
<li><a href="javax/swing/tree/AbstractLayoutCache.NodeDimensions.html" title="class in javax.swing.tree" target="classFrame">AbstractLayoutCache.NodeDimensions</a></li>
<li><a href="java/util/AbstractList.html" title="class in java.util" target="classFrame">AbstractList</a></li>
<li><a href="javax/swing/AbstractListModel.html" title="class in javax.swing" target="classFrame">AbstractListModel</a></li>
<li><a href="java/util/AbstractMap.html" title="class in java.util" target="classFrame">AbstractMap</a></li>
<li><a href="java/util/AbstractMap.SimpleEntry.html" title="class in java.util" target="classFrame">AbstractMap.SimpleEntry</a></li>
<li><a href="java/util/AbstractMap.SimpleImmutableEntry.html" title="class in java.util" target="classFrame">AbstractMap.SimpleImmutableEntry</a></li>
<li><a href="javax/xml/bind/helpers/AbstractMarshallerImpl.html" title="class in javax.xml.bind.helpers" target="classFrame">AbstractMarshallerImpl</a></li>
<li><a href="java/lang/AbstractMethodError.html" title="class in java.lang" target="classFrame">AbstractMethodError</a></li>
<li><a href="java/util/concurrent/locks/AbstractOwnableSynchronizer.html" title="class in java.util.concurrent.locks" target="classFrame">AbstractOwnableSynchronizer</a></li>
<li><a href="java/util/prefs/AbstractPreferences.html" title="class in java.util.prefs" target="classFrame">AbstractPreferences</a></li>
<li><a href="javax/annotation/processing/AbstractProcessor.html" title="class in javax.annotation.processing" target="classFrame">AbstractProcessor</a></li>
<li><a href="java/util/AbstractQueue.html" title="class in java.util" target="classFrame">AbstractQueue</a></li>
<li><a href="java/util/concurrent/locks/AbstractQueuedLongSynchronizer.html" title="class in java.util.concurrent.locks" target="classFrame">AbstractQueuedLongSynchronizer</a></li>
<li><a href="java/util/concurrent/locks/AbstractQueuedSynchronizer.html" title="class in java.util.concurrent.locks" target="classFrame">AbstractQueuedSynchronizer</a></li>
<li><a href="javax/swing/plaf/nimbus/AbstractRegionPainter.html" title="class in javax.swing.plaf.nimbus" target="classFrame">AbstractRegionPainter</a></li>
<li><a href="javax/swing/plaf/nimbus/AbstractRegionPainter.PaintContext.html" title="class in javax.swing.plaf.nimbus" target="classFrame">AbstractRegionPainter.PaintContext</a></li>
<li><a href="javax/swing/plaf/nimbus/AbstractRegionPainter.PaintContext.CacheMode.html" title="enum in javax.swing.plaf.nimbus" target="classFrame">AbstractRegionPainter.PaintContext.CacheMode</a></li>
<li><a href="javax/script/AbstractScriptEngine.html" title="class in javax.script" target="classFrame">AbstractScriptEngine</a></li>
<li><a href="java/nio/channels/spi/AbstractSelectableChannel.html" title="class in java.nio.channels.spi" target="classFrame">AbstractSelectableChannel</a></li>
<li><a href="java/nio/channels/spi/AbstractSelectionKey.html" title="class in java.nio.channels.spi" target="classFrame">AbstractSelectionKey</a></li>
<li><a href="java/nio/channels/spi/AbstractSelector.html" title="class in java.nio.channels.spi" target="classFrame">AbstractSelector</a></li>
<li><a href="java/util/AbstractSequentialList.html" title="class in java.util" target="classFrame">AbstractSequentialList</a></li>
<li><a href="java/util/AbstractSet.html" title="class in java.util" target="classFrame">AbstractSet</a></li>
<li><a href="javax/swing/AbstractSpinnerModel.html" title="class in javax.swing" target="classFrame">AbstractSpinnerModel</a></li>
<li><a href="javax/swing/table/AbstractTableModel.html" title="class in javax.swing.table" target="classFrame">AbstractTableModel</a></li>
<li><a href="javax/lang/model/util/AbstractTypeVisitor6.html" title="class in javax.lang.model.util" target="classFrame">AbstractTypeVisitor6</a></li>
<li><a href="javax/lang/model/util/AbstractTypeVisitor7.html" title="class in javax.lang.model.util" target="classFrame">AbstractTypeVisitor7</a></li>
<li><a href="javax/lang/model/util/AbstractTypeVisitor8.html" title="class in javax.lang.model.util" target="classFrame">AbstractTypeVisitor8</a></li>
<li><a href="javax/swing/undo/AbstractUndoableEdit.html" title="class in javax.swing.undo" target="classFrame">AbstractUndoableEdit</a></li>
<li><a href="javax/xml/bind/helpers/AbstractUnmarshallerImpl.html" title="class in javax.xml.bind.helpers" target="classFrame">AbstractUnmarshallerImpl</a></li>
<li><a href="org/w3c/dom/views/AbstractView.html" title="interface in org.w3c.dom.views" target="classFrame"><span class="interfaceName">AbstractView</span></a></li>
<li><a href="javax/swing/text/AbstractWriter.html" title="class in javax.swing.text" target="classFrame">AbstractWriter</a></li>
<li><a href="java/nio/channels/AcceptPendingException.html" title="class in java.nio.channels" target="classFrame">AcceptPendingException</a></li>
<li><a href="java/security/AccessControlContext.html" title="class in java.security" target="classFrame">AccessControlContext</a></li>
<li><a href="java/security/AccessControlException.html" title="class in java.security" target="classFrame">AccessControlException</a></li>
<li><a href="java/security/AccessController.html" title="class in java.security" target="classFrame">AccessController</a></li>
<li><a href="java/nio/file/AccessDeniedException.html" title="class in java.nio.file" target="classFrame">AccessDeniedException</a></li>
<li><a href="java/rmi/AccessException.html" title="class in java.rmi" target="classFrame">AccessException</a></li>
<li><a href="javax/accessibility/Accessible.html" title="interface in javax.accessibility" target="classFrame"><span class="interfaceName">Accessible</span></a></li>
<li><a href="javax/accessibility/AccessibleAction.html" title="interface in javax.accessibility" target="classFrame"><span class="interfaceName">AccessibleAction</span></a></li>
<li><a href="javax/accessibility/AccessibleAttributeSequence.html" title="class in javax.accessibility" target="classFrame">AccessibleAttributeSequence</a></li>
<li><a href="javax/accessibility/AccessibleBundle.html" title="class in javax.accessibility" target="classFrame">AccessibleBundle</a></li>
<li><a href="javax/accessibility/AccessibleComponent.html" title="interface in javax.accessibility" target="classFrame"><span class="interfaceName">AccessibleComponent</span></a></li>
<li><a href="javax/accessibility/AccessibleContext.html" title="class in javax.accessibility" target="classFrame">AccessibleContext</a></li>
<li><a href="javax/accessibility/AccessibleEditableText.html" title="interface in javax.accessibility" target="classFrame"><span class="interfaceName">AccessibleEditableText</span></a></li>
<li><a href="javax/accessibility/AccessibleExtendedComponent.html" title="interface in javax.accessibility" target="classFrame"><span class="interfaceName">AccessibleExtendedComponent</span></a></li>
<li><a href="javax/accessibility/AccessibleExtendedTable.html" title="interface in javax.accessibility" target="classFrame"><span class="interfaceName">AccessibleExtendedTable</span></a></li>
<li><a href="javax/accessibility/AccessibleExtendedText.html" title="interface in javax.accessibility" target="classFrame"><span class="interfaceName">AccessibleExtendedText</span></a></li>
<li><a href="javax/accessibility/AccessibleHyperlink.html" title="class in javax.accessibility" target="classFrame">AccessibleHyperlink</a></li>
<li><a href="javax/accessibility/AccessibleHypertext.html" title="interface in javax.accessibility" target="classFrame"><span class="interfaceName">AccessibleHypertext</span></a></li>
<li><a href="javax/accessibility/AccessibleIcon.html" title="interface in javax.accessibility" target="classFrame"><span class="interfaceName">AccessibleIcon</span></a></li>
<li><a href="javax/accessibility/AccessibleKeyBinding.html" title="interface in javax.accessibility" target="classFrame"><span class="interfaceName">AccessibleKeyBinding</span></a></li>
<li><a href="java/lang/reflect/AccessibleObject.html" title="class in java.lang.reflect" target="classFrame">AccessibleObject</a></li>
<li><a href="javax/accessibility/AccessibleRelation.html" title="class in javax.accessibility" target="classFrame">AccessibleRelation</a></li>
<li><a href="javax/accessibility/AccessibleRelationSet.html" title="class in javax.accessibility" target="classFrame">AccessibleRelationSet</a></li>
<li><a href="javax/accessibility/AccessibleResourceBundle.html" title="class in javax.accessibility" target="classFrame">AccessibleResourceBundle</a></li>
<li><a href="javax/accessibility/AccessibleRole.html" title="class in javax.accessibility" target="classFrame">AccessibleRole</a></li>'''
  
import re
from html.parser import HTMLParser
from html.entities import name2codepoint
from urllib import request


if __name__ == "__main__":
	url = "file:///C:/docs/api/allclasses-frame.html"
	with request.urlopen(url) as data:		#打开url并获取信息，获取到的数据为bytes类型
		data = data.read()
	#parser = MyHTMLParser()
	#parser.feed(data.decode('utf-8'))	





p = re.compile(r'target="classFrame">(.*)</a>', re.MULTILINE)
for one in p.findall(content):
    print(one)

p = re.compile(r'<span class="interfaceName">(.*)</span>', re.MULTILINE)
for one in p.findall(content):
    print(one)


